server:
  port: ${PORT:${SERVER_PORT:8089}}

spring:
  application:
    name: api-gateway
  cloud:    
    gateway:
      default-filters: TokenRelay
      routes:
        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/** , /v3/api-docs/catalog
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/** , /v3/api-docs/user
  security:
    oauth2:
      client:
        provider:
          api-gateway-client:
            issuer-uri: http://localhost:8181/realms/vinylSound
        registration:
          api-gateway-client:
            client-id: api-gateway-client
            client-secret: Vzqeufbo5fJarPBXO77udm3Biz3pLoTa
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8089/login/oauth2/code/keycloak   

info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
