server:
  port: ${PORT:${SERVER_PORT:8089}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/api/catalog/** , /admin/catalog/** , /v3/api-docs/catalog
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/** , /admin/users/** , /user/service/** , /v3/api-docs/user
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/user/payment/** , /v3/api-docs/payment
        - id: order
          uri: lb://order
          predicates:
            - Path=/user/order/** , /user/cart/** , /v3/api-docs/order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/vinylSound
info:
  app:
    name: ${spring.application.name}
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
