server:
  port: ${PORT:8085}
spring:
  application:
    name: order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/order?createDatabaseIfNotExist=true
    username: user-vinylSound
    password: pass-vinylSound
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
info:
  application:
    name: catalog
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  email:
    sender: vinylsoundinformation@gmail.com
    password: rxez fzfp fudk nfji
