server:
  port: ${PORT:8085}
spring:
  application:
    name: order
  datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-4.cne24kciiqv0.us-east-2.rds.amazonaws.com:3307/order
    username: Grupo5
    password: !Grupo5password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
info:
  application:
    name: order
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
email:
  sender: vinylsoundinformation@gmail.com
  password: rxez fzfp fudk nfji
  host: smtp.gmail.com
  debug: true
