server:
  port: ${PORT:8084}
spring:
  application:
    name: payment
datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vinylSound?createDatabaseIfNotExist=true
    username: user-vinylSound
    password: pass-vinylSound
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
info:
  application:
    name: payment
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
