server:
  port: ${PORT:8082}
spring:
  application:
    name: user
  security:
    oauth2:
      client:
        registration:
          keycloak:
            serverUrl: http://localhost:8181
            realm: vinylSound
            client-id: user-client
            client-secret: **********
            #client-secret: WSYHBndG6DLUWpBk2ii5xT6u7D781lFg
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/vinylSound
            tokenUri: http://localhost:8181/realms/vinylSound/protocol/openid-connect/token
info:
  application:
    name: user
    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
